[supabase]
url = 'https://ihcltjkppdylwqsdtdkp.supabase.co'
key = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloY2x0amtwcGR5bHdxc2R0ZGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjY4NDcwNTUsImV4cCI6MjA0MjQyMzA1NX0.1qQXBBm8tO0Pe98O9DVZX6TymGncMH7jZMF8a3BuGgI'

[gutenberg]
url = "https://gutendex.com/books?search="
