cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    kubeops:
      email: seokjoon.kim@bespinglobal.com
      failed_login_attempts: 0
      logged_in: false
      name: kubeops
      password: "$2b$12$Q49u.0P1x8u3h6nlqDS3ReRZhdHXsigBGXAQO/Neo5vecEys2x0ke"
pre-authorized:
  emails:
  - seokjoon.kim@bespinglobal.com
